spring:
  profiles:
    active: dev
  #开启restful风格
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
  redis:
    host: 114.116.234.63
    password: shiwo2002625
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
##分页pageHelper
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
