#开发环境配置

# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easycontract?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

# mybatis配置
mybatis:
  mapper-locations: classpath:bjtu/pt/easycontracts/mapper/*.xml    # mapper映射文件位置
  type-aliases-package: bjtu.pt.easycontracts.pojo    # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
    map-underscore-to-camel-case: true

#日志配置
logging:
  level:
    root: info
    bjtu.pt.easycontracts: debug
  file:
    name: log/blog-dev.log

